In [1]:
path="IMDB-Movie-Data.csv"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df1=pd.read_csv(path)

In [4]:
df1.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [5]:
df1

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
21,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
23,24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
24,25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
25,26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
28,29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
29,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
971,972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
972,973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
974,975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
975,976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
976,977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
977,978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
979,980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
982,983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
984,985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
985,986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [11]:
df1[df1["Rank"]>100]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
100,101,Legend,"Biography,Crime,Drama",Identical twin gangsters Ronald and Reginald K...,Brian Helgeland,"Tom Hardy, Emily Browning, Taron Egerton, Paul...",2015,132,7.0,108836,1.87,55.0
101,102,Thor,"Action,Adventure,Fantasy",The powerful but arrogant god Thor is cast out...,Kenneth Branagh,"Chris Hemsworth, Anthony Hopkins, Natalie Port...",2011,115,7.0,570814,181.02,57.0
102,103,The Martian,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
103,104,Contratiempo,"Crime,Mystery,Thriller",A young businessman faces a lawyer trying to p...,Oriol Paulo,"Mario Casas, Ana Wagener, José Coronado, Bárba...",2016,106,7.9,7204,NaN,NaN
104,105,The Man from U.N.C.L.E.,"Action,Adventure,Comedy","In the early 1960s, CIA agent Napoleon Solo an...",Guy Ritchie,"Henry Cavill, Armie Hammer, Alicia Vikander, E...",2015,116,7.3,202973,45.43,56.0
105,106,Hell or High Water,"Crime,Drama,Thriller",A divorced father and his ex-con older brother...,David Mackenzie,"Chris Pine, Ben Foster, Jeff Bridges, Gil Birm...",2016,102,7.7,115546,26.86,88.0
106,107,The Comedian,Comedy,A look at the life of an aging insult comic na...,Taylor Hackford,"Robert De Niro, Leslie Mann, Danny DeVito, Edi...",2016,120,5.4,1954,1.66,40.0
107,108,The Legend of Tarzan,"Action,Adventure,Drama","Tarzan, having acclimated to life in London, i...",David Yates,"Alexander Skarsgård, Rory J. Saper, Christian ...",2016,110,6.3,117590,126.59,44.0
108,109,All We Had,Drama,A mother struggles to make a better life for h...,Katie Holmes,"Eve Lindley, Richard Kind, Mark Consuelos, Kat...",2016,105,5.8,1004,NaN,48.0
109,110,Ex Machina,"Drama,Mystery,Sci-Fi",A young programmer is selected to participate ...,Alex Garland,"Alicia Vikander, Domhnall Gleeson, Oscar Isaac...",2014,108,7.7,339797,25.44,78.0
110,111,The Belko Experiment,"Action,Horror,Thriller","In a twisted social experiment, 80 Americans a...",Greg McLean,"John Gallagher Jr., Tony Goldwyn, Adria Arjona...",2016,89,6.3,3712,10.16,44.0
111,112,12 Years a Slave,"Biography,Drama,History","In the antebellum United States, Solomon North...",Steve McQueen,"Chiwetel Ejiofor, Michael Kenneth Williams, Mi...",2013,134,8.1,486338,56.67,96.0
112,113,The Bad Batch,"Romance,Sci-Fi",A dystopian love story in a Texas wasteland an...,Ana Lily Amirpour,"Keanu Reeves, Jason Momoa, Jim Carrey, Diego Luna",2016,118,6.1,512,NaN,65.0
113,114,300,"Action,Fantasy,War",King Leonidas of Sparta and a force of 300 men...,Zack Snyder,"Gerard Butler, Lena Headey, David Wenham, Domi...",2006,117,7.7,637104,210.59,52.0
114,115,Harry Potter and the Deathly Hallows: Part 2,"Adventure,Drama,Fantasy","Harry, Ron and Hermione search for Voldemort's...",David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, M...",2011,130,8.1,590595,380.96,87.0
115,116,Office Christmas Party,Comedy,When his uptight CEO sister threatens to shut ...,Josh Gordon,"Jason Bateman, Olivia Munn, T.J. Miller,Jennif...",2016,105,5.8,30761,54.73,42.0
116,117,The Neon Demon,"Horror,Thriller",When aspiring model Jesse moves to Los Angeles...,Nicolas Winding Refn,"Elle Fanning, Christina Hendricks, Keanu Reeve...",2016,118,6.2,50359,1.33,51.0
117,118,Dangal,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,NaN
118,119,10 Cloverfield Lane,"Drama,Horror,Mystery","After getting in a car accident, a woman is he...",Dan Trachtenberg,"John Goodman, Mary Elizabeth Winstead, John Ga...",2016,104,7.2,192968,71.90,76.0
119,120,Finding Dory,"Animation,Adventure,Comedy","The friendly but forgetful blue tang fish, Dor...",Andrew Stanton,"Ellen DeGeneres, Albert Brooks,Ed O'Neill, Kai...",2016,97,7.4,157026,486.29,77.0
120,121,Miss Peregrine's Home for Peculiar Children,"Adventure,Drama,Family",When Jacob discovers clues to a mystery that s...,Tim Burton,"Eva Green, Asa Butterfield, Samuel L. Jackson,...",2016,127,6.7,101058,87.24,57.0
121,122,Divergent,"Adventure,Mystery,Sci-Fi",In a world divided by factions based on virtue...,Neil Burger,"Shailene Woodley, Theo James, Kate Winslet, Ja...",2014,139,6.7,362093,150.83,48.0
122,123,Mike and Dave Need Wedding Dates,"Adventure,Comedy,Romance",Two hard-partying brothers place an online ad ...,Jake Szymanski,"Zac Efron, Adam Devine, Anna Kendrick, Aubrey ...",2016,98,6.0,53183,46.01,51.0
123,124,Boyka: Undisputed IV,Action,In the fourth installment of the fighting fran...,Todor Chapkanov,"Scott Adkins, Teodora Duhovnikova, Alon Aboutb...",2016,86,7.4,10428,NaN,NaN
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
125,126,The Jungle Book,"Adventure,Drama,Family",After a threat from the tiger Shere Khan force...,Jon Favreau,"Neel Sethi, Bill Murray, Ben Kingsley, Idris Elba",2016,106,7.5,198243,364.00,77.0
126,127,Transformers: Age of Extinction,"Action,Adventure,Sci-Fi",Autobots must escape sight from a bounty hunte...,Michael Bay,"Mark Wahlberg, Nicola Peltz, Jack Reynor, Stan...",2014,165,5.7,255483,245.43,32.0
127,128,Nerve,"Adventure,Crime,Mystery",A high school senior finds herself immersed in...,Henry Joost,"Emma Roberts, Dave Franco, Emily Meade, Miles ...",2016,96,6.6,69651,38.56,58.0
128,129,Mamma Mia!,"Comedy,Family,Musical",The story of a bride-to-be trying to find her ...,Phyllida Lloyd,"Meryl Streep, Pierce Brosnan, Amanda Seyfried,...",2008,108,6.4,153481,143.70,51.0
129,130,The Revenant,"Adventure,Drama,Thriller",A frontiersman on a fur trading expedition in ...,Alejandro González Iñárritu,"Leonardo DiCaprio, Tom Hardy, Will Poulter, Do...",2015,156,8.0,499424,183.64,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
971,972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
972,973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
974,975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
975,976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
976,977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
977,978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
979,980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
982,983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
984,985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
985,986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [13]:
df1["Rank"]<100

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999    False
Name: Rank, Length: 1000, dtype: bool

In [14]:
print(df1)

     Rank                                    Title  \
0       1                  Guardians of the Galaxy
1       2                               Prometheus
2       3                                    Split
3       4                                     Sing
4       5                            Suicide Squad
5       6                           The Great Wall
6       7                               La La Land
7       8                                 Mindhorn
8       9                       The Lost City of Z
9      10                               Passengers
10     11  Fantastic Beasts and Where to Find Them
11     12                           Hidden Figures
12     13                                Rogue One
13     14                                    Moana
14     15                                 Colossal
15     16                  The Secret Life of Pets
16     17                            Hacksaw Ridge
17     18                             Jason Bourne
18     19                                     Lion
19     20                                  Arrival
20     21                                     Gold
21     22                    Manchester by the Sea
22     23                           Hounds of Love
23     24                                   Trolls
24     25             Independence Day: Resurgence
25     26                          Paris pieds nus
26     27                  Bahubali: The Beginning
27     28                               Dead Awake
28     29                                 Bad Moms
29     30                         Assassin's Creed
..    ...                                      ...
970   971                        Texas Chainsaw 3D
971   972                                Disturbia
972   973                             Rock of Ages
973   974                                 Scream 4
974   975                           Queen of Katwe
975   976               My Big Fat Greek Wedding 2
976   977                              Dark Places
977   978                            Amateur Night
978   979           It's Only the End of the World
979   980                       The Skin I Live In
980   981                     Miracles from Heaven
981   982                                    Annie
982   983                      Across the Universe
983   984                            Let's Be Cops
984   985                                      Max
985   986                            Your Highness
986   987                      Final Destination 5
987   988                             Endless Love
988   989                                  Martyrs
989   990                                    Selma
990   991           Underworld: Rise of the Lycans
991   992                         Taare Zameen Par
992   993                     Take Me Home Tonight
993   994                 Resident Evil: Afterlife
994   995                                Project X
995   996                     Secret in Their Eyes
996   997                          Hostel: Part II
997   998                   Step Up 2: The Streets
998   999                             Search Party
999  1000                               Nine Lives

                          Genre  \
0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
5      Action,Adventure,Fantasy
6            Comedy,Drama,Music
7                        Comedy
8    Action,Adventure,Biography
9       Adventure,Drama,Romance
10     Adventure,Family,Fantasy
11      Biography,Drama,History
12      Action,Adventure,Sci-Fi
13   Animation,Adventure,Comedy
14          Action,Comedy,Drama
15   Animation,Adventure,Comedy
16      Biography,Drama,History
17              Action,Thriller
18              Biography,Drama
19         Drama,Mystery,Sci-Fi
20     Adventure,Drama,Thriller
21                        Drama
22           Crime,Drama,Horror
23   Animation,Adventure,Comedy
24      Action,Adventure,Sci-Fi
25                       Comedy
26       Action,Adventure,Drama
27              Horror,Thriller
28                       Comedy
29       Action,Adventure,Drama
..                          ...
970             Horror,Thriller
971      Drama,Mystery,Thriller
972        Comedy,Drama,Musical
973              Horror,Mystery
974       Biography,Drama,Sport
975       Comedy,Family,Romance
976      Drama,Mystery,Thriller
977                      Comedy
978                       Drama
979              Drama,Thriller
980      Biography,Drama,Family
981         Comedy,Drama,Family
982       Drama,Fantasy,Musical
983                      Comedy
984            Adventure,Family
985    Adventure,Comedy,Fantasy
986             Horror,Thriller
987               Drama,Romance
988                      Horror
989     Biography,Drama,History
990    Action,Adventure,Fantasy
991          Drama,Family,Music
992        Comedy,Drama,Romance
993     Action,Adventure,Horror
994                      Comedy
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy

                                           Description               Director  \
0    A group of intergalactic criminals are forced ...             James Gunn
1    Following clues to the origin of mankind, a te...           Ridley Scott
2    Three girls are kidnapped by a man with a diag...     M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...   Christophe Lourdelet
4    A secret government agency recruits some of th...             David Ayer
5    European mercenaries searching for black powde...            Yimou Zhang
6    A jazz pianist falls for an aspiring actress i...        Damien Chazelle
7    A has-been actor best known for playing the ti...             Sean Foley
8    A true-life drama, centering on British explor...             James Gray
9    A spacecraft traveling to a distant colony pla...          Morten Tyldum
10   The adventures of writer Newt Scamander in New...            David Yates
11   The story of a team of female African-American...         Theodore Melfi
12   The Rebel Alliance makes a risky move to steal...         Gareth Edwards
13   In Ancient Polynesia, when a terrible curse in...           Ron Clements
14   Gloria is an out-of-work party girl forced to ...        Nacho Vigalondo
15   The quiet life of a terrier named Max is upend...           Chris Renaud
16   WWII American Army Medic Desmond T. Doss, who ...             Mel Gibson
17   The CIA's most dangerous former operative is d...        Paul Greengrass
18   A five-year-old Indian boy gets lost on the st...            Garth Davis
19   When twelve mysterious spacecraft appear aroun...       Denis Villeneuve
20   Kenny Wells, a prospector desperate for a luck...         Stephen Gaghan
21   A depressed uncle is asked to take care of his...       Kenneth Lonergan
22   A cold-blooded predatory couple while cruising...              Ben Young
23   After the Bergens invade Troll Village, Poppy,...             Walt Dohrn
24   Two decades after the first Independence Day i...        Roland Emmerich
25   Fiona visits Paris for the first time to assis...         Dominique Abel
26   In ancient India, an adventurous and daring ma...         S.S. Rajamouli
27   A young woman must save herself and her friend...         Phillip Guzman
28   When three overworked and under-appreciated mo...              Jon Lucas
29   When Callum Lynch explores the memories of his...          Justin Kurzel
..                                                 ...                    ...
970  A young woman travels to Texas to collect an i...        John Luessenhop
971  A teen living under house arrest becomes convi...            D.J. Caruso
972  A small town girl and a city boy meet on the S...          Adam Shankman
973  Ten years have passed, and Sidney Prescott, wh...             Wes Craven
974  A Ugandan girl sees her world rapidly change a...              Mira Nair
975  A Portokalos family secret brings the beloved ...             Kirk Jones
976  Libby Day was only eight years old when her fa...  Gilles Paquet-Brenner
977  Guy Carter is an award-winning graduate studen...           Lisa Addario
978  Louis (Gaspard Ulliel), a terminally ill write...           Xavier Dolan
979  A brilliant plastic surgeon, haunted by past t...        Pedro Almodóvar
980  A young girl suffering from a rare digestive d...        Patricia Riggen
981  A foster kid, who lives with her mean foster m...             Will Gluck
982  The music of the Beatles and the Vietnam War f...           Julie Taymor
983  Two struggling pals dress as police officers f...        Luke Greenfield
984  A Malinois dog that helped American Marines in...             Boaz Yakin
985  When Prince Fabious's bride is kidnapped, he g...     David Gordon Green
986  Survivors of a suspension-bridge collapse lear...           Steven Quale
987  The story of a privileged girl and a charismat...            Shana Feste
988  A young woman's quest for revenge against the ...         Pascal Laugier
989  A chronicle of Martin Luther King's campaign t...           Ava DuVernay
990  An origins story centered on the centuries-old...     Patrick Tatopoulos
991  An eight-year-old boy is thought to be a lazy ...             Aamir Khan
992  Four years after graduation, an awkward high s...          Michael Dowse
993  While still out to destroy the evil Umbrella C...     Paul W.S. Anderson
994  3 high school seniors throw a birthday party t...        Nima Nourizadeh
995  A tight-knit team of rising investigators, alo...              Billy Ray
996  Three American college students studying abroa...               Eli Roth
997  Romantic sparks occur between two dance studen...             Jon M. Chu
998  A pair of friends embark on a mission to reuni...         Scot Armstrong
999  A stuffy businessman finds himself trapped ins...       Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
5        Matt Damon, Tian Jing, Willem Dafoe, Andy Lau  2016
6    Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....  2016
7    Essie Davis, Andrea Riseborough, Julian Barrat...  2016
8    Charlie Hunnam, Robert Pattinson, Sienna Mille...  2016
9    Jennifer Lawrence, Chris Pratt, Michael Sheen,...  2016
10   Eddie Redmayne, Katherine Waterston, Alison Su...  2016
11   Taraji P. Henson, Octavia Spencer, Janelle Mon...  2016
12   Felicity Jones, Diego Luna, Alan Tudyk, Donnie...  2016
13   Auli'i Cravalho, Dwayne Johnson, Rachel House,...  2016
14   Anne Hathaway, Jason Sudeikis, Austin Stowell,...  2016
15   Louis C.K., Eric Stonestreet, Kevin Hart, Lake...  2016
16   Andrew Garfield, Sam Worthington, Luke Bracey,...  2016
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016
18   Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...  2016
19   Amy Adams, Jeremy Renner, Forest Whitaker,Mich...  2016
20   Matthew McConaughey, Edgar Ramírez, Bryce Dall...  2016
21   Casey Affleck, Michelle Williams, Kyle Chandle...  2016
22   Emma Booth, Ashleigh Cummings, Stephen Curry,S...  2016
23   Anna Kendrick, Justin Timberlake,Zooey Deschan...  2016
24   Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...  2016
25   Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...  2016
26   Prabhas, Rana Daggubati, Anushka Shetty,Tamann...  2015
27   Jocelin Donahue, Jesse Bradford, Jesse Borrego...  2016
28   Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...  2016
29   Michael Fassbender, Marion Cotillard, Jeremy I...  2016
..                                                 ...   ...
970  Alexandra Daddario, Tania Raymonde, Scott East...  2013
971  Shia LaBeouf, David Morse, Carrie-Anne Moss, S...  2007
972  Julianne Hough, Diego Boneta, Tom Cruise, Alec...  2012
973  Neve Campbell, Courteney Cox, David Arquette, ...  2011
974  Madina Nalwanga, David Oyelowo, Lupita Nyong'o...  2016
975  Nia Vardalos, John Corbett, Michael Constantin...  2016
976  Charlize Theron, Nicholas Hoult, Christina Hen...  2015
977  Jason Biggs, Janet Montgomery,Ashley Tisdale, ...  2016
978  Nathalie Baye, Vincent Cassel, Marion Cotillar...  2016
979  Antonio Banderas, Elena Anaya, Jan Cornet,Mari...  2011
980  Jennifer Garner, Kylie Rogers, Martin Henderso...  2016
981  Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...  2014
982  Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...  2007
983  Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...  2014
984  Thomas Haden Church, Josh Wiggins, Luke Kleint...  2015
985  Danny McBride, Natalie Portman, James Franco, ...  2011
986  Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...  2011
987  Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...  2014
988  Morjana Alaoui, Mylène Jampanoï, Catherine Bég...  2008
989  David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...  2014
990  Rhona Mitra, Michael Sheen, Bill Nighy, Steven...  2009
991  Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...  2007
992  Topher Grace, Anna Faris, Dan Fogler, Teresa P...  2011
993  Milla Jovovich, Ali Larter, Wentworth Miller,K...  2010
994  Thomas Mann, Oliver Cooper, Jonathan Daniel Br...  2012
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
5                  103     6.1   56036               45.13       42.0
6                  128     8.3  258682              151.06       93.0
7                   89     6.4    2490                 NaN       71.0
8                  141     7.1    7188                8.01       78.0
9                  116     7.0  192177              100.01       41.0
10                 133     7.5  232072              234.02       66.0
11                 127     7.8   93103              169.27       74.0
12                 133     7.9  323118              532.17       65.0
13                 107     7.7  118151              248.75       81.0
14                 109     6.4    8612                2.87       70.0
15                  87     6.6  120259              368.31       61.0
16                 139     8.2  211760               67.12       71.0
17                 123     6.7  150823              162.16       58.0
18                 118     8.1  102061               51.69       69.0
19                 116     8.0  340798              100.50       81.0
20                 120     6.7   19053                7.22       49.0
21                 137     7.9  134213               47.70       96.0
22                 108     6.7    1115                 NaN       72.0
23                  92     6.5   38552              153.69       56.0
24                 120     5.3  127553              103.14       32.0
25                  83     6.8     222                 NaN        NaN
26                 159     8.3   76193                6.50        NaN
27                  99     4.7     523                0.01        NaN
28                 100     6.2   66540              113.08       60.0
29                 115     5.9  112813               54.65       36.0
..                 ...     ...     ...                 ...        ...
970                 92     4.8   37060               34.33       62.0
971                105     6.9  193491               80.05        NaN
972                123     5.9   64513               38.51       47.0
973                111     6.2  108544               38.18       52.0
974                124     7.4    6753                8.81       73.0
975                 94     6.0   20966               59.57       37.0
976                113     6.2   31634                 NaN       39.0
977                 92     5.0    2229                 NaN       38.0
978                 97     7.0   10658                 NaN       48.0
979                120     7.6  108772                3.19       70.0
980                109     7.0   12048               61.69       44.0
981                118     5.3   27312               85.91       33.0
982                133     7.4   95172               24.34       56.0
983                104     6.5  112729               82.39       30.0
984                111     6.8   21405               42.65       47.0
985                102     5.6   87904               21.56       31.0
986                 92     5.9   88000               42.58       50.0
987                104     6.3   33688               23.39       30.0
988                 99     7.1   63785                 NaN       89.0
989                128     7.5   67637               52.07        NaN
990                 92     6.6  129708               45.80       44.0
991                165     8.5  102697                1.20       42.0
992                 97     6.3   45419                6.92        NaN
993                 97     5.9  140900               60.13       37.0
994                 88     6.7  164088               54.72       48.0
995                111     6.2   27585                 NaN       45.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
998                 93     5.6    4881                 NaN       22.0
999                 87     5.3   12435               19.64       11.0

[1000 rows x 12 columns]

In [15]:
df1.tail()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
Rank                  1000 non-null int64
Title                 1000 non-null object
Genre                 1000 non-null object
Description           1000 non-null object
Director              1000 non-null object
Actors                1000 non-null object
Year                  1000 non-null int64
Runtime (Minutes)     1000 non-null int64
Rating                1000 non-null float64
Votes                 1000 non-null int64
Revenue (Millions)    872 non-null float64
Metascore             936 non-null float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.8+ KB

In [19]:
df1.shape

(1000, 12)

In [24]:
temp_df1=df1.append(df1)

In [34]:
temp_df1.shape

AttributeError: 'function' object has no attribute 'shape'

In [26]:
tt=dict()

In [29]:
temp_df1=temp_df1.drop_duplicates

In [35]:
df1.shape

(1000, 12)

In [43]:
temp_df1=df1.append(df1)

In [44]:
temp_df1.shape

(2000, 12)

In [45]:
temp_df1.drop_duplicates()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
21,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
23,24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
24,25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
25,26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
28,29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
29,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
971,972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
972,973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
974,975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
975,976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
976,977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
977,978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
979,980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
982,983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
984,985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
985,986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [46]:
temp_df1.shape

(2000, 12)

In [47]:
temp_df1=temp_df1.drop_duplicates()

In [48]:
temp_df1.shape

(1000, 12)

In [49]:
df1.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [52]:
df1.rename(columns={"Title":"Movie_Names"},inplace=True)

In [53]:
df1.columns

Index(['Rank', 'Movie_Names', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [57]:
df1.isnull()

,Rank,Movie_Names,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,True,True
26,False,False,False,False,False,False,False,False,False,False,False,True
27,False,False,False,False,False,False,False,False,False,False,False,True
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
970,False,False,False,False,False,False,False,False,False,False,False,False
971,False,False,False,False,False,False,False,False,False,False,False,True
972,False,False,False,False,False,False,False,False,False,False,False,False
973,False,False,False,False,False,False,False,False,False,False,False,False
974,False,False,False,False,False,False,False,False,False,False,False,False
975,False,False,False,False,False,False,False,False,False,False,False,False
976,False,False,False,False,False,False,False,False,False,False,True,False
977,False,False,False,False,False,False,False,False,False,False,True,False
978,False,False,False,False,False,False,False,False,False,False,True,False
979,False,False,False,False,False,False,False,False,False,False,False,False
980,False,False,False,False,False,False,False,False,False,False,False,False
981,False,False,False,False,False,False,False,False,False,False,False,False
982,False,False,False,False,False,False,False,False,False,False,False,False
983,False,False,False,False,False,False,False,False,False,False,False,False
984,False,False,False,False,False,False,False,False,False,False,False,False
985,False,False,False,False,False,False,False,False,False,False,False,False
986,False,False,False,False,False,False,False,False,False,False,False,False
987,False,False,False,False,False,False,False,False,False,False,False,False
988,False,False,False,False,False,False,False,False,False,False,True,False
989,False,False,False,False,False,False,False,False,False,False,False,True
990,False,False,False,False,False,False,False,False,False,False,False,False
991,False,False,False,False,False,False,False,False,False,False,False,False
992,False,False,False,False,False,False,False,False,False,False,False,True
993,False,False,False,False,False,False,False,False,False,False,False,False
994,False,False,False,False,False,False,False,False,False,False,False,False
995,False,False,False,False,False,False,False,False,False,False,True,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,True,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [56]:
df1

,Rank,Movie_Names,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
21,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
23,24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
24,25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
25,26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
28,29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
29,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
971,972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
972,973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
974,975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
975,976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
976,977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
977,978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
979,980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
982,983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
984,985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
985,986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [58]:
df1.isnull().sum()

Rank                    0
Movie_Names             0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [72]:
re=df1['Revenue (Millions)']

In [73]:
re

0      333.13
1      126.46
2      138.12
3      270.32
4      325.02
5       45.13
6      151.06
7         NaN
8        8.01
9      100.01
10     234.02
11     169.27
12     532.17
13     248.75
14       2.87
15     368.31
16      67.12
17     162.16
18      51.69
19     100.50
20       7.22
21      47.70
22        NaN
23     153.69
24     103.14
25        NaN
26       6.50
27       0.01
28     113.08
29      54.65
        ...
970     34.33
971     80.05
972     38.51
973     38.18
974      8.81
975     59.57
976       NaN
977       NaN
978       NaN
979      3.19
980     61.69
981     85.91
982     24.34
983     82.39
984     42.65
985     21.56
986     42.58
987     23.39
988       NaN
989     52.07
990     45.80
991      1.20
992      6.92
993     60.13
994     54.72
995       NaN
996     17.54
997     58.01
998       NaN
999     19.64
Name: Revenue (Millions), Length: 1000, dtype: float64

In [74]:
re.dropna()

0      333.13
1      126.46
2      138.12
3      270.32
4      325.02
5       45.13
6      151.06
8        8.01
9      100.01
10     234.02
11     169.27
12     532.17
13     248.75
14       2.87
15     368.31
16      67.12
17     162.16
18      51.69
19     100.50
20       7.22
21      47.70
23     153.69
24     103.14
26       6.50
27       0.01
28     113.08
29      54.65
30      60.31
31      10.64
32     155.33
        ...
960      2.32
961      0.01
962     26.81
963      0.09
967     10.14
969     89.29
970     34.33
971     80.05
972     38.51
973     38.18
974      8.81
975     59.57
979      3.19
980     61.69
981     85.91
982     24.34
983     82.39
984     42.65
985     21.56
986     42.58
987     23.39
989     52.07
990     45.80
991      1.20
992      6.92
993     60.13
994     54.72
996     17.54
997     58.01
999     19.64
Name: Revenue (Millions), Length: 872, dtype: float64

In [75]:
re.mean()

82.95637614678897